import { Geist, Geist_Mono, Nunito_Sans } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import TopBar from "@/components/bars/top-bar"
import SideBar from "@/components/bars/side-bar"


const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});
const nunito = Nunito_Sans({
    subsets: ["latin"],
});



export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en" >
	  <body className={`${nunito.className}`}>
	      <TopBar />
	      <SideBar />

	      {children}
	  </body>
      </html>
  );
}
